### ISSUE TITLE
urls stop working after activation

### ISSUE THREAD

**Issue by tofuSCHNITZEL** [adigitalife/yourls-case-insensitive#7]
After activating the plugin all urls I try to open result in following PHP error:

9919#0: *963701 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Error: Call to undefined method ezSQL_pdo_YOURLS::has_infos() in /var/www/vhosts/xxx/httpdocs/user/plugins/case-insensitive/plugin.php:52
Stack trace:
#0 /var/www/vhosts/xxx/httpdocs/user/plugins/case-insensitive/plugin.php(36): insensitive_get_keyword_infos('qrchk')
#1 /var/www/vhosts/xxx/httpdocs/includes/functions-plugins.php(150): insensitive_get_keyword_info(false, 'qrchk', 'url', false)
#2 /var/www/vhosts/xxx/httpdocs/includes/functions.php(465): yourls_apply_filter('shunt_get_keywo...', false, 'qrchk', 'url', false)
#3 /var/www/vhosts/xxx/httpdocs/includes/functions.php(492): yourls_get_keyword_info('qrchk', 'url', false)
#4 /var/www/vhosts/xxx/httpdocs/yourls-go.php(17): yourls_get_keyword_longurl('qrchk')
#5 /var/www/vhosts/xxx/httpdocs/yourls-loader.php(37): require_once('/var/www/vhosts...')
#6 {main}
thrown in /var/www/vhosts/xxx/httpdocs/user/plugins/case-insensitive/plugin.php on line 52" while reading response header from upstream

**Comment by vivid-pixel** [comment]
Same! I didn't think to check functionality after activating this plugin so my short URLs have been broken several days and I accumulated a **huge** error_log. There was another similar plugin that I will try for the meantime.

`[27-Oct-2018 19:53:08 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method ezSQL_pdo_YOURLS::has_infos() in /home/shortror/public_html/user/plugins/case-insensitive/plugin.php:52
Stack trace:
#0 /home/shortror/public_html/user/plugins/case-insensitive/plugin.php(36): insensitive_get_keyword_infos('rxafo')
#1 /home/shortror/public_html/includes/functions-plugins.php(150): insensitive_get_keyword_info(false, 'rxafo', 'url', false)
#2 /home/shortror/public_html/includes/functions.php(465): yourls_apply_filter('shunt_get_keywo...', false, 'rxafo', 'url', false)
#3 /home/shortror/public_html/includes/functions.php(492): yourls_get_keyword_info('rxafo', 'url', false)
#4 /home/shortror/public_html/yourls-go.php(17): yourls_get_keyword_longurl('rxafo')
#5 /home/shortror/public_html/yourls-loader.php(37): require_once('/home/shortror/...')
#6 {main}
  thrown in /home/shortror/public_html/user/plugins/case-insensitive/plugin.php on line 52
[27-Oct-2018 19:53:08 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method ezSQL_pdo_YOURLS::has_infos() in /home/shortror/public_html/user/plugins/case-insensitive/plugin.php:52
Stack trace:`

**Comment by vivid-pixel** [comment]
For anyone else having this problem, I installed [the other case insensitive plugin](https://github.com/seandrickson/YOURLS-Case-Insensitive/) and while it didn't break my installation, it doesn't seem to have any effect at all. That plugin is quite outdated which is why I went with this one first, but I suppose for now I'll be using neither! :(

**Comment by adigitalife** [comment]
Sorry, this is an old plugin that works fine for me on YOURLS 1.7.1.  Perhaps it's not compatible with the latest versions?

**Comment by vivid-pixel** [comment]
I am using version 1.7.2, so seems kinda slim, but maybe.

**Comment by eneerge** [comment]
Same issue here.  I'll see if I can easily fix and post a fork.

**Comment by eneerge** [comment]
Alright, so it seems this plugin will not work unless you set the shortening method to "62" in the yourls config.php.

When it builds the regex string, if method 62 is not set in the config file, it leaves out uppercase values in the regex and this plugin never runs because the the redirection logic never executes.

To fix, be sure to update this line in the "yourls/user/config.php" file.
`define( 'YOURLS_URL_CONVERT', 62 );`

FYI: This is mentioned on the main page of this plugin, but some how I did not notice it.

**Comment by vivid-pixel** [comment]
> Alright, so it seems this plugin will not work unless you set the shortening method to "62" in the yourls config.php.

While that's true, it still throws the PHP fatal error about ezSQL_pdo_YOURLS::has_infos() so that seems to be unrelated. I think that's the only reason I set Yourls to 31 in the first place, just to not accept capital letters since this plugin wouldn't work properly.
